"""users table

Revision ID: 6c86494e14e3
Revises: ea2141667021
Create Date: 2022-12-07 14:00:24.268511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c86494e14e3'
down_revision = 'ea2141667021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('option1', sa.String(length=140), nullable=True),
    sa.Column('option2', sa.String(length=140), nullable=True),
    sa.Column('option3', sa.String(length=140), nullable=True),
    sa.Column('option4', sa.String(length=140), nullable=True),
    sa.Column('answers_option1', sa.String(length=140), nullable=True),
    sa.Column('answers_option2', sa.String(length=140), nullable=True),
    sa.Column('answers_option3', sa.String(length=140), nullable=True),
    sa.Column('answers_option4', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index('ix_post_timestamp')

    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index('ix_post_timestamp', ['timestamp'], unique=False)

    op.drop_table('questions')
    # ### end Alembic commands ###
